/**
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input: s = "abcd" t = "abcde"
 * 
 * Output: e
 * 
 * Explanation: 'e' is the letter that was added.
 * 
 * 
 * 
 * 
 */

public class solution389 {
    public char findTheDifference(String s, String t) {
        // solution3
        // int result = 0;
        // for (int i : t.toCharArray()) {
        // result += i;
        // }
        // for (int i : s.toCharArray()) {
        // result -= i;
        // }
        // return (char) result;

        // solution2
        // Map<Integer, Integer> store = new HashMap<>();
        // for (int i : t.toCharArray()) {
        // if (!store.containsKey(i)) {
        // store.put(i, 1);
        // } else {
        // store.put(i, store.get(i) + 1);
        // }
        // }
        // for (int i : s.toCharArray()) {
        // if (store.containsKey(i)) {
        // if (store.get(i) - 1 == 0) {
        // store.remove(i);
        // } else {
        // store.put(i, store.get(i) - 1);
        // }
        // }
        // }
        // int firstKey = store.keySet().iterator().next();
        // return (char) firstKey;

        // solution1
        String first = s;
        String second = t;
        int[] alph = new int[26];
        for (int i = 0; i < second.length(); i++) {
            alph[second.charAt(i) - 'a']++;
        }
        for (int i = 0; i < first.length(); i++) {
            alph[first.charAt(i) - 'a']--;
        }
        for (int i = 0; i < alph.length; i++) {
            if (alph[i] != 0) {
                int result = 'a' + i;
                return (char) result;
            }
        }
        return ' ';
    }

    public static void main(String[] args) {
        solution389 a = new solution389();
        String s = "abcde";
        String t = "abcdef";
        System.out.println(a.findTheDifference(s, t));
    }
}